
export const primaryDiagnosisOptions = [
  'Inguinal Hernia (left groin)',
  'Inguinal Hernia (right side)',
  'Bilateral Inguinal Hernias with Hydrocele',
  'Hypospadias (anterior)',
  'Hypospadias (midshaft)',
  'Hypospadias (posterior)',
  'Hypospadias (penoscrotal)',
  'Hypospadias (distal)',
  'Varicose Veins (R leg)',
  'Varicose Veins (L leg)',
  'Varicose Veins (bilateral)',
  'Hemorrhoids (Grade II)',
  'Hemorrhoids (Grade III)',
  'Hemorrhoids (Grade IV)',
  'Right Kidney Stone',
  'Ureteric Stone (Lt side)',
  'Ureteric Stone (Rt side)',
  'Staghorn Kidney Stone',
  'Undescended Testis (Left)',
  'Undescended Testis (Right)',
  'Phimosis with meatal stenosis',
  'Phimosis (tight foreskin)',
  'Meatal Stenosis',
  'Burn Injury',
  'Post-Burn Contracture',
  'Diabetic Foot Ulcer',
  'Necrotizing Fasciitis',
  'Compartment Syndrome',
  'Facial Fracture',
  'Mandible Fracture',
  'Testicular Tumor',
  'Bladder Neck Obstruction (BPH)',
  'End-Stage Renal Disease',
  'COVID-19 Pneumonia',
  'Dengue Hemorrhagic Fever',
  'Small Bowel Obstruction',
  'Appendiceal Mass',
  'Abdominal Tuberculosis'
];
