
export const labsRadiologyOptions = [
  'VCUG (voiding cystogram)',
  'Pre-op labs',
  'Post-op labs',
  'Complete Blood Count (CBC)',
  'Basic Metabolic Panel (BMP)',
  'Liver Function Tests (LFTs)',
  'Coagulation Studies (PT/PTT)',
  'Urinalysis',
  'Urine Culture',
  'Blood Culture',
  'X-ray Chest',
  'X-ray Abdomen',
  'X-ray Pelvis',
  'Ultrasound Abdomen',
  'Ultrasound Pelvis',
  'Ultrasound Scrotum',
  'CT Scan Abdomen',
  'CT Scan Pelvis',
  'CT Scan Chest',
  'MRI',
  'Doppler Studies',
  'ECG',
  'Echocardiogram',
  'Arterial Blood Gas (ABG)',
  'Venous Blood Gas (VBG)',
  'Blood Glucose',
  'HbA1c',
  'Electrolytes',
  'Renal Function Tests',
  'Thyroid Function Tests',
  'Cardiac Enzymes',
  'Inflammatory Markers (ESR, CRP)',
  'Tumor Markers',
  'Hepatitis Panel',
  'HIV Testing',
  'Covid-19 Testing'
];
