
export const antibioticOptions = [
  'Inj. Meropenem + Vancomycin + Colistin',
  'Inj. Imipenem-Cilastatin + Linezolid',
  'Inj. Doripenem + Tigecycline + Polymyxin B',
  'Inj. Ertapenem + Daptomycin',
  'Inj. Ceftaroline + Teicoplanin',
  'Inj. Ceftolozane-Tazobactam + Quinupristin-Dalfopristin',
  'Inj. Meropenem-Vaborbactam + Fosfomycin',
  'Inj. Imipenem-Relebactam + Ceftazidime-Avibactam',
  'Inj. Plazomicin + Eravacycline',
  'Inj. Omadacycline + Lefamulin',
  'Inj. Tedizolid + Oritavancin',
  'Inj. Dalbavancin + Ceftobiprole',
  'Inj. Aztreonam-Avibactam + Cefiderocol',
  'Inj. Rezafungin + Isavuconazole (for fungal co-infection)',
  'Inj. Micafungin + Posaconazole (for invasive mycoses)',
  'Inj. Anidulafungin + Voriconazole',
  'None (no significant infection risk)',
  'Oral Linezolid + Tedizolid (step-down therapy)'
];

export const otherMedicationsOptions = [
  'Inj. Fentanyl + Remifentanil (high-potency analgesics)',
  'Tab. Pregabalin + Gabapentin (neuropathic pain)',
  'Inj. Ketamine + Dexmedetomidine (anesthesia adjuncts)',
  'Tab. Oxycodone + Tapentadol (controlled-release opioids)',
  'Inj. Propofol + Sevoflurane (premium anesthetics)',
  'Tab. Duloxetine + Venlafaxine (antidepressants)',
  'Inj. Octreotide + Lanreotide (somatostatin analogs)',
  'Tab. Apixaban + Rivaroxaban (novel anticoagulants)',
  'Inj. Erythropoietin + Darbepoetin (erythropoiesis stimulants)',
  'Tab. Sirolimus + Tacrolimus (immunosuppressants)',
  'Inj. Bevacizumab + Ranibizumab (anti-VEGF agents)',
  'Tab. Lenalidomide + Pomalidomide (immunomodulators)',
  'Inj. Rituximab + Infliximab (monoclonal antibodies)',
  'Tab. Sorafenib + Sunitinib (tyrosine kinase inhibitors)',
  'Inj. Pegfilgrastim + Filgrastim (growth factors)',
  'Tab. Cinacalcet + Paricalcitol (calcium metabolism)',
  'Inj. Terlipressin + Norepinephrine (vasopressors)',
  'Tab. Ambrisentan + Bosentan (endothelin antagonists)',
  'Inj. Iloprost + Epoprostenol (prostacyclins)',
  'Tab. Macitentan + Selexipag (pulmonary vasodilators)',
  'Inj. Human Albumin + Immunoglobulins (plasma products)',
  'Tab. Everolimus + Temsirolimus (mTOR inhibitors)',
  'Inj. Pembrolizumab + Nivolumab (checkpoint inhibitors)',
  'Tab. Ibrutinib + Venetoclax (targeted therapy)',
  'Inj. Tocilizumab + Sarilumab (IL-6 inhibitors)',
  'None',
  'As needed (PRN)',
  'Continue specialized protocols'
];
