
export const surgeryOptions = [
  'Hernioplasty',
  'Herniotomy (open hernia repair)',
  'Bilateral Herniotomy + Hydrocele repair',
  'Hypospadias Repair + Circumcision',
  'One-stage Hypospadias Repair',
  'Hypospadias Repair + Meatotomy + Meatoplasty',
  'Endovenous Laser Ablation (EVLA)',
  'Varicose Vein Laser Ablation',
  'Laser Hemorrhoidectomy + Sphincterotomy',
  'Laser Hemorrhoidectomy',
  'Open Hemorrhoidectomy',
  'PCNL (Right kidney) + DJ stent',
  'URSL (Laser lithotripsy) + DJ stenting',
  'URSL + DJ stent placement',
  'Left Orchidopexy',
  'Right Orchidopexy + Herniotomy',
  'Circumcision + Meatoplasty',
  'Circumcision + Meatotomy',
  'Circumcision',
  'Meatoplasty + Re-circumcision',
  'Burn Wound Dressings (repeated)',
  'Contracture Release Surgery (Z-plasty)',
  'Debridement + Split-Thickness Skin Graft',
  'Rotational Flap Closure',
  'Surgical Debridement (multiple sessions)',
  'Fasciotomy + Debridement',
  'ORIF with Plating (Facial bones)',
  'ORIF with Plating (Jaw fracture)',
  'Radical Orchiectomy',
  'Cystoscopy + Bladder Neck Incision + Urethral Dilatation',
  'Hemodialysis (repeated sessions)',
  'ICU Care, Oxygen/Ventilator',
  'ICU Support, Fluids, Transfusion',
  'Nasogastric decompression; IV fluids',
  'IV antibiotics; Observation',
  'Anti-tubercular Therapy (ATT); Nutrition support'
];
